version: '3.7'
services:
  elasticsearch:
    restart: always
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment: 
    - xpack.security.enabled=true
    - discovery.type=single-node
    - ELASTIC_USERNAME=elastic
    - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    ports:
      - $ELASTIC_PORT:9200
    networks:
      - elk_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  setup-passwords:
    image: appropriate/curl
    container_name: setup-passwords
    command: >
      sh -c "sleep 60 &&
      curl -s -X PUT -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' http://elasticsearch:9200/_security/user/kibana_system/_password -d '{\"password\":\"$KIBANA_PASSWORD\"}' &&
      curl -s -X PUT -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' http://elasticsearch:9200/_security/user/beats_system/_password -d '{\"password\":\"$BEATS_PASSWORD\"}'"
    depends_on:
      - elasticsearch

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=$KIBANA_PASSWORD
    ports:
      - $KIBANA_PORT:5601
    networks:
      - elk_network
    links: 
    - elasticsearch
    depends_on: 
    - elasticsearch

networks:
  elk_network:
    driver: bridge
